#!/usr/bin/env bash

set -e
export MIST_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

runner="local"

cmd=$1
shift

while [[ $# > 1 ]]
do
  key="$1"

  case ${key} in
    --namespace)
      namespace="$2"
      shift
      ;;

  esac

shift
done

if [ "${cmd}" == 'start' ]
then
  #hash=$(echo -n ${namespace} | md5sum | awk '{print $1}') 
  hash=${namespace}
  python ${MIST_HOME}/scripts/create-singularity-json.py ${hash}
  ~/.local/bin/nd-singularity -s singularity-21.jiwiredev.com deploy -f ${MIST_HOME}/configs/pca-mist-worker-${hash}.json -r --retry=99
elif [ "${cmd}" == 'stop' ]
then
  echo "stop"
  #hash=$(echo -n ${namespace} | md5sum | awk '{print $1}') 
  hash=${namespace}
  curl -X DELETE singularity-21.jiwiredev.com/singularity/api/requests/request/dev-pca-mist-worker-${hash}
fi